# Generated by Django 4.2.2 on 2023-07-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_category_product_front_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trending',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='product',
            name='front_description',
            field=models.TextField(max_length=30),
        ),
    ]
