# Generated by Django 4.2.2 on 2023-07-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='front_description',
            field=models.TextField(max_length=200),
        ),
    ]
